name: Build and Deploy

on:
  push:
    branches:
      - devenv  # Change this to the default branch of your repository

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x  # Change this to the .NET version you need

    - name: Build API
      run: |
        # Add your build commands here
        dotnet build -c Release
      working-directory: path/to/api  # Change to the API project folder

    - name: Build Service
      run: |
        # Add your build commands here
        msbuild /t:Build /p:Configuration=Release
      working-directory: path/to/service  # Change to the service project folder

    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          path/to/api/bin/Release
          path/to/service/bin/Release

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: artifacts

    - name: Deploy API
      run: |
        # Add your deployment script for the API here
        # e.g., PowerShell or batch script
        # Example: .\deploy-api.ps1
      working-directory: path/to/api

    - name: Deploy Service
      run: |
        # Add your deployment script for the service here
        # e.g., PowerShell or batch script
        # Example: .\deploy-service.ps1
      working-directory: path/to/service
